version: '3.8'

services:
  db:
    image: mysql:8.1
    container_name: redmine-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: redmine
      MYSQL_USER: redmine
      MYSQL_PASSWORD: redminepassword
    volumes:
      - db-data:/var/lib/mysql

  redmine:
    image: redmine:5.0
    container_name: redmine-app
    restart: always
    depends_on:
      - db
    ports:
      - "8080:3000"
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redminepassword
volumes:
  db-data:
