#!/bin/bash

# 現在日時を取得
Y=$(date +%Y)
M=$(date +%m)
YM="$Y / $M"

# 曜日を定義
days=" Mon Tue Wed Thu Fri Sat Sun"
width="${#days}"

# カレンダー上部を表示
echo; printf "%*s\n" $(((${#YM} + $width) / 2)) "$YM"
echo; echo $days

# 当月の日数を取得
days_in_month=$(date -d "$Y-$M-01 +1 month -1 day" "+%d")

# 当月1日の曜日を取得(1: Mon, 2: Tue, ... 7:Sun)
first_day=$(date -d "$Y-$M-01" "+%u")

# 最初の曜日に対応する空白を出力
for ((i = 1; i < first_day; i++)); do
  printf "    "
done

# 日付をループで出力
for ((day = 1; day <= days_in_month; day++)); do
  printf "%3d " "$day" # 日付を3桁で表示
  # 曜日が日曜日(7)なら改行
  if (( (day + first_day -1) % 7 == 0 )); then
    echo
  fi
done

echo; echo
  
