#!/bin/bash
# 本日日付.mdファイル(YYYYMMDD.md)作成と編集

DATE=$(date +%Y%m%d)
FILE=$DATE.md

if [ -f "$FILE" ]; then
  echo "すでに$FILEファイルが存在します: "
else
  touch "$FILE"
  echo "$FILEファイルを作成しました: "
fi


echo -n "$FILEを編集しますか？(編集する場合は「y」を入力): "
read FLG

if [[ "$FLG" = "y" || "$FLG" = "Y" ]]; then
  vim "$FILE"
else
  echo "処理を終了しました: "
fi

